---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcf-ers-repo
  - name: version

outputs:
  - name: build-output

run:
  path: pcf-ers-demo/ci/tasks/build.sh
  args: [
    --input-dir, pcf-ers-rep,
    --output-dir, build-output,
    --version-file, version/number,
    --artifactId, pcf-ers-demo,
    --packaging, jar
  ]
