---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  CF_MANIFEST_HOST: attendees

inputs:
  - name: pcf-ers-repo
  - name: app-release
  - name: version

outputs:
  - name: prepare-manifest
run:
  path: pcf-ers-repo/ci/tasks/prepare-manifest.sh
  args: [
    --input-dir, app-release,
    --output-dir, prepare-manifest,
    --version-file, version/number,
    --input-manifest, pcf-ers-repo/manifest.yml,
    --artifactId, pcf-ers-demo,
    --packaging, jar
  ]
