---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcf-ers-repo
  - name: app-release 

run:
  path: pcf-ers-repo/ci/tasks/test.sh
