resources:
  - name: pcf-ers-repo
    type: git
    source:
      uri: {{github-pcf-ers-uri}}
      branch: {{github-pcf-ers-branch}}

  - name: version
    type: semver
    source:
      bucket: {{s3-bucket-version}}
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      initial_version: 1.0.0
      endpoint: {{s3-endpoint}}

  - name: cf-test
    type: cf
    source:
      api: {{cf-pws-api}}
      username: {{cf-pws-username}}
      password: {{cf-pws-password}}
      organization: {{cf-pws-org}}
      space: {{cf-pws-space}}
      skip_cert_check: true

  - name: cf-prod
    type: cf
    source:
      api: {{cf-pcf1-api}}
      username: {{cf-pcf1-username}}
      password: {{cf-pcf1-password}}
      organization: {{cf-pcf1-org}}
      space: {{cf-pcf1-space}}
      skip_cert_check: true

  - name: app-release
    type: s3
    source:
      bucket: {{s3-bucket-releases}}
      regexp: pcf-ers-demo-(.*).jar
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

jobs:
  - name: build-app
    public: true
    serial: true
    plan:
      - get: pcf-ers-repo
        trigger: true
      - get: version
        params: {bump: patch}
      - task: build
        file: pcf-ers-repo/ci/build.yml
      - put: app-release
        params: {from: build-output/pcf-ers-demo-.*.jar}
      - put: version
        params: { file: version/number }

