resources:
  - name: pcf-ers-repo
    type: git
    source:
      uri: {{github-pcf-ers-uri}}
      branch: {{github-pcf-ers-branch}}

  - name: version
    type: semver
    source:
      bucket: {{s3-bucket-version}}
      key: current-version
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      initial_version: 0.0.1
      endpoint: {{s3-endpoint}}

  - name: app-release
    type: s3
    source:
      bucket: {{s3-bucket-releases}}
      regexp: pcf-ers-demo-(.*).jar
      access_key_id: {{s3-access-key-id}}
      secret_access_key: {{s3-secret-access-key}}
      endpoint: {{s3-endpoint}}

  - name: cf-test
    type: cf
    source:
      api: {{cf-pws-api}}
      username: {{cf-pws-username}}
      password: {{cf-pws-password}}
      organization: {{cf-pws-org}}
      space: {{cf-pws-space}}
      skip_cert_check: true

  - name: cf-prod
    type: cf
    source:
      api: {{cf-pcf1-api}}
      username: {{cf-pcf1-username}}
      password: {{cf-pcf1-password}}
      organization: {{cf-pcf1-org}}
      space: {{cf-pcf1-space}}
      skip_cert_check: true

jobs:
  - name: build-app
    public: true
    serial: true
    plan:
      - get: pcf-ers-repo
        #trigger: true
      - get: version
        params: {bump: patch}
      - task: build
        file: pcf-ers-repo/ci/tasks/build.yml
      - put: app-release
        params: { file: build-output/target/pcf-ers-demo-*.jar}
      - put: version
        params: { file: version/number }

  - name: deploy-test
    plan:
      - get: app-release
        passed: [build-app]
      - get: pcf-ers-repo
        passed: [build-app]
      - get: version
      - task: prepare-manifest
        file: pcf-ers-repo/ci/tasks/prepare-manifest.yml
      - put: cf-test
        params:
          manifest: prepare-manifest/manifest.yml

  - name: test-app
    plan:
      - get: pcf-ers-repo
        passed: [deploy-test]
      - task: test
        file: pcf-ers-repo/ci/tasks/test.yml

  - name: blue-deploy-prod
    plan:
      - get: pcf-ers-repo
        passed: [test-app]
      - get: app-release
      - get: version
      - task: prod-manifest
        file: pcf-ers-repo/ci/tasks/prod-manifest.yml
      - put: cf-prod
        params:
          manifest: prod-manifest/manifest.yml

  - name: finalize-blue-green
    serial: true
    plan:
      - get: pcf-ers-repo
        #passed: [blue-deploy-prod]
      - task: finalize-deploy
        file: pcf-ers-repo/ci/tasks/finalize-deploy.yml
        params:
          CF_API_ENDPOINT: {{cf-pws-api}}
          CF_USER: {{cf-pws-username}}
          CF_PWD: {{cf-pws-password}}
          CF_ORG: {{cf-pws-org}}
          CF_SPACE: {{cf-pws-space}}
          #CF_API_ENDPOINT: {{cf-pcf1-api}}
          #CF_USER: {{cf-pcf1-username}}
          #CF_PWD: {{cf-pcf1-password}}
          #CF_ORG: {{cf-pcf1-org}}
          #CF_SPACE: {{cf-pcf1-space}}


